### PR TITLE
fix(design): correct `DaffStatusableDirective` default status logic

### LINKED ISSUE #4170: User provided value to `status` is not working in `DaffStatusableDirective`
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

User provided value to `status` is not working in `DaffStatusableDirective`

### Environment

- Daffodil version: 0.90.0
- Angular version:
- Browser(s):
- Node version: run `node --version`
- Operating system:

### Steps to reproduce

Steps to reproduce:
1. Serve `design-land`
2. Set a `defaultStatus` on the button component
3. See in the statusable-button example that examples with a different status from the `defaultStatus` is not respected.

### Expected behavior

User provided status should be respected.

### Actual behavior

2. The logic in `ngOnInit` is wrong, overriding user inputs instead of applying defaults only when needed

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist

- [x] Commit message follows our [contributing guidelines](https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit)
- [ ] Tests added/updated (for bug fixes/features)
- [ ] Documentation added/updated (for bug fixes/features)

## PR Type

- [x] Bug fix
- [ ] Feature
- [ ] Style update
- [ ] Refactor
- [ ] Test
- [ ] Build
- [ ] CI
- [ ] Docs
- [ ] Performance
- [ ] Other (please describe)

## Current behavior

Fixes: #4170

## Breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/design/src/core/statusable/statusable.directive.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export class DaffStatusableDirective implements DaffStatusable, OnChanges, OnIni
   ngOnInit() {
     validateStatus(this.status);
 
-    if (this.status !== this.defaultStatus && this.defaultStatus) {
+    if (this.defaultStatus && !this.status) {
```
Comment (damienwebdev) [inline libs/design/src/core/statusable/statusable.directive.ts:125]: Can you add a test checking the status?

**Review by damienwebdev — CHANGES_REQUESTED** [review]

File: libs/design/src/core/statusable/statusable.directive.ts (hunk 1 above)
Comment (xelaint) [reply libs/design/src/core/statusable/statusable.directive.ts:125]: Does the `default.directive.spec.ts` test not cover this?

Comment (damienwebdev) [reply libs/design/src/core/statusable/statusable.directive.ts:125]: I would have expected it to, but clearly it must not have otherwise this PR wouldn't exist.

Comment (damienwebdev) [reply libs/design/src/core/statusable/statusable.directive.ts:125]: I think you should write a test replicating the issue you saw BEFORE this change, and then prove that this change remedies that issue.

Comment (xelaint) [reply libs/design/src/core/statusable/statusable.directive.ts:125]: Added

**Review by damienwebdev — APPROVED** [review]
lgtm
