### PR TITLE
fix(design): fix duplicate track keys in DaffTreeComponent by using unique node IDs

### LINKED ISSUE #4114: Duplicate track keys in `DaffTreeComponent`
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Duplicate track keys in `DaffTreeComponent`.

`The provided track expression resulted in duplicated keys for a given collection. Adjust the tracking expression such that it uniquely identifies all the items in the collection.`

`trackByTreeElement` is resulting in duplicated keys. Using `el.title` might not be the best since there could be duplicate titles (e.g. Overview)

### Environment

- Daffodil version: 0.90
- Angular version: 20
- Browser(s):
- Node version: run `node --version`
- Operating system:

### Steps to reproduce

Steps to reproduce:
1. Run a watch on `design` (npx nx run @daffodil/design:build --watch)
2. Run serve `npx ng s daffio`
3. Convert `*ngFor="let node of flatTree; trackBy: trackByTreeElement"` to `@for` expression
4. See in console the warnings

### Expected behavior

`trackByTreeElement` should result in all unique keys

### Actual behavior

```
The provided track expression resulted in duplicated keys for a given collection. Adjust the tracking expression such that it uniquely identifies all the items in the collection.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by F4tal1t**
## PR Checklist

- [x] Commit message follows our [contributing guidelines](https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit)
- [x] Tests added/updated (for bug fixes/features)
- [x] Documentation added/updated (for bug fixes/features)

## PR Type

- [x] Bug fix

## Current behavior
The trackByTreeElement function in `DaffTreeComponent` was returning `el.title`, which could result in duplicate keys when multiple tree nodes have the same title (e.g., "Overview"). This caused Angular's change detection to produce warnings about duplicate track keys, especially when using the new @for control flow syntax.

Fixes: #4114 

## New behavior

- Updated `trackByTreeElement` in `tree.component.ts` to return `el.id` instead of `el.title`, ensuring unique track keys since id is guaranteed to be unique per tree node.

- Modified the template in `tree.component.html` to use Angular's new `@for` syntax with track node.id for modern control flow.
- Added a unit test in ` tree.component.spec.ts`  to verify `trackByTreeElement` returns the correct unique identifier.

## Breaking change?

- [ ] Yes
- [x] No

## Additional context
The fix maintains backward compatibility with `*ngFor` while resolving the duplicate track key warnings in `@for`. All tests pass, and the change follows Daffodil's contribution guidelines. The `id` field is populated uniquely by the `flattenTree` utility, ensuring no duplicates.

### CODE REVIEW

File: libs/design/tree/src/tree/tree.component.ts [hunk 1]
```diff
@@ -141,7 +141,7 @@ export class DaffTreeComponent implements OnInit, OnChanges {
    * The track-by function used to reduce tree-item re-renders
    */
   trackByTreeElement(index: number, el: any): any {
-    return el.title;
+    return el.id;
   }
```
Comment (griest024) [inline libs/design/tree/src/tree/tree.component.ts]: This method is unused, just remove it and the test. I prefer the inline track implementation when its as simple as `node.id`

**Review by griest024 — CHANGES_REQUESTED** [review]

File: libs/design/tree/src/tree/tree.component.ts (hunk 1 above)
Comment (F4tal1t) [reply libs/design/tree/src/tree/tree.component.ts]: made new changes as requested, is it good to go now?

**Review by griest024 — APPROVED** [review]
lgtm! thanks for the PR!

**Review by damienwebdev — APPROVED** [review]
lgtm
