### PR TITLE
fix(design): paginator is hydration incompatible

### LINKED ISSUE #3426: Make design components hydration compatible
We should avoid direct DOM manipulation in design components as this will [break hydration](https://angular.dev/guide/hydration#direct-dom-manipulation). ~~Its also an open issue that [template outlets break hydration and require a workaround](https://github.com/angular/angular/issues/50543)~~ fixed in angular 20. This issue should track the various instances of design components that currently have hydration-incompatible implementations:

- paginator: https://github.com/graycoreio/daffodil/blob/25766422ef010b4c336025e56570025d0ac24c9c/libs/design/paginator/src/paginator/paginator.component.ts#L71-L72

### PR DESCRIPTION
**Pull request by griest024**
## PR Checklist

- [ ] Commit message follows our [contributing guidelines](https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit)
- [ ] Tests added/updated (for bug fixes/features)
- [ ] Documentation added/updated (for bug fixes/features)

## PR Type

- [ ] Bug fix
- [ ] Feature
- [ ] Style update
- [ ] Refactor
- [ ] Test
- [ ] Build
- [ ] CI
- [ ] Docs
- [ ] Performance
- [ ] Other (please describe)

## Current behavior

Fixes: #3426
Part of: # 

## Breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: libs/design/paginator/src/paginator/paginator.component.ts [hunk 1]
```diff
@@ -86,6 +75,11 @@ export class DaffPaginatorComponent implements OnChanges {
    */
   @Input() queryParam = 'page';
 
+  /**
+   * The aria label.
+   */
+  @Input() ariaLabel: string;
```
Comment (damienwebdev) [inline libs/design/paginator/src/paginator/paginator.component.ts]: Can this be `aria-label` instead? Will it automatically pick up the label using the native attribute?

**Review by damienwebdev — CHANGES_REQUESTED** [review]

File: libs/design/paginator/src/paginator/paginator.component.ts (hunk 1 above)
Comment (griest024) [reply libs/design/paginator/src/paginator/paginator.component.ts]: no input names should not collide with DOM attributes. However I had forgotten to add the host binding so I've done that

Comment (xelaint) [reply libs/design/paginator/src/paginator/paginator.component.ts]: Can you set this the HostBinding on the `host` property instead?

File: libs/design/paginator/src/paginator/paginator.component.html [hunk 2]
```diff
@@ -2,15 +2,15 @@
   <button type="button" class="daff-paginator__previous"
     [disabled]="_disablePrev"
     tabindex="0"
-    attr.aria-label="Go to Previous Page of {{_paginatorId}} Paginator"
+    attr.aria-label="Go to Previous Page of {{ariaLabel}} Paginator"
```
Comment (damienwebdev) [inline libs/design/paginator/src/paginator/paginator.component.html]: I was looking at various paginator implementations and I believe that adding the label in here is non-normative.

https://a11ymatters.com/pattern/pagination/
https://design-system.w3.org/components/pagination.html

I believe this should solely read: "Go to Previous Page".

@xelaint

**Review by damienwebdev — CHANGES_REQUESTED** [review]

File: libs/design/paginator/src/paginator/paginator.component.html (hunk 2 above)
Comment (xelaint) [reply libs/design/paginator/src/paginator/paginator.component.html]: Yeah, I don't think the aria-label is necessary in the component. `aria-label` should not be set on `<daff-paginator>` like it currently is. Instead, it needs to be wrapped in a `<nav>` element where the `aria-label` is set on it.

This is more of a documentation issue since:

Current example is:

```
<daff-paginator aria-label="Search results page" [numberOfPages]="numberOfPages" [currentPage]="currentPage" (notifyPageChange)="onPageChange($event)"></daff-paginator>
```

Correct example should be:

```
<nav aria-label="Search Results Pagination">
  <daff-paginator [numberOfPages]="numberOfPages" [currentPage]="currentPage" (notifyPageChange)="onPageChange($event)"></daff-paginator>
</nav>
```

Comment (damienwebdev) [reply libs/design/paginator/src/paginator/paginator.component.html]: Ok. To finalize, the appropriate change here would be to make the buttons say:

"Go to page 'x'"
"Go to next page"
"Go to previous page"

And any reference to the aria label would be removed.

Comment (griest024) [reply libs/design/paginator/src/paginator/paginator.component.html]: changed

**Review by damienwebdev — APPROVED** [review]
Lgtm
